    # See https://pre-commit.com for more information
    # See https://pre-commit.com/hooks.html for more hooks
    repos:
        -   repo: https://github.com/pre-commit/pre-commit-hooks
            rev: v5.0.0
            hooks:
            -   id: check-added-large-files
            -   id: check-case-conflict
            -   id: check-executables-have-shebangs
            -   id: check-merge-conflict
            -   id: check-shebang-scripts-are-executable
            -   id: check-symlinks
            -   id: check-yaml
            -   id: debug-statements
                exclude: tests/
            -   id: destroyed-symlinks
            -   id: end-of-file-fixer
                files: \.(py|sh|rst|yml|yaml)$
            -   id: mixed-line-ending
            -   id: trailing-whitespace
                files: \.(py|sh|rst|yml|yaml)$
        -   repo: https://github.com/psf/black
            rev: 25.1.0
            hooks:
            -   id: black
        -   repo: https://github.com/PyCQA/flake8
            rev: 7.3.0
            hooks:
            -   id: flake8
                additional_dependencies: [
                    'flake8-blind-except',
                    'flake8-docstrings',
                    'flake8-bugbear',
                    'flake8-comprehensions',
                    'flake8-docstrings',
                    'flake8-implicit-str-concat',
                    'pydocstyle>=5.0.0',
                ]
